# Comparative Study

## Importing Libraries

In [2]:
from utils.models import FisherLDA, Perceptron, LogReg
import pandas as pd
import numpy as np

## Perceptron

In [3]:
%%capture
EPOCHS = 100
LEARNING_RATE = 0.3
pm1_details = {
    "training_accuracy": 0,
    "testing_accuracy_avg": 0,
    "precision_avg": 0,
    "f1_avg": 0,
    "recall_avg": 0
}
pm2_details = {
    "training_accuracy": 0,
    "testing_accuracy_avg": 0,
    "precision_avg": 0,
    "f1_avg": 0,
    "recall_avg": 0
}
pm3_details = {
    "training_accuracy": 0,
    "testing_accuracy_avg": 0,
    "precision_avg": 0,
    "f1_avg": 0,
    "recall_avg": 0
}
pm4_details = {
    "training_accuracy": 0,
    "testing_accuracy_avg": 0,
    "precision_avg": 0,
    "f1_avg": 0,
    "recall_avg": 0
}

for _ in range(10):
    # Read the csv file
    dataset = pd.read_csv('../dataset.csv')
    
    # Convert cancer type into a new column
    dataset["cancer_type"] = pd.factorize(dataset["diagnosis"])[0]
    dataset["cancer_type"] = dataset["cancer_type"].replace(0, -1)
    dataset.head()

    # Remove ID and diagnosis from the dataset
    dataset.drop(['id', 'diagnosis'], axis=1, inplace=True)

    # Drop NA rows because in first one we shouldn't use NA
    dropped_dataset = dataset.dropna()

    # Get pm2 ready
    shuffled_dataset2 = dropped_dataset.sample(frac=1, random_state=2)
    shuffled_dataset2.head()

    # Get pm4 ready
    dataset = pd.read_csv('../dataset.csv')
    # Shuffling the dataset column wise
    dataset_column_shuffled = dataset.sample(frac=1, axis=1)
    dataset_column_shuffled.head()
    # Convert cancer type into a new column
    dataset_column_shuffled["cancer_type"] = pd.factorize(dataset_column_shuffled["diagnosis"])[0]
    dataset_column_shuffled["cancer_type"] = dataset_column_shuffled["cancer_type"].replace(0, -1)
    # Remove ID and diagnosis from the dataset
    dataset_column_shuffled.drop(['id', 'diagnosis'], axis=1, inplace=True)
    dataset_column_shuffled.head()

    pm_1 = Perceptron(dataset=dropped_dataset)
    print("Executing model : pm_1")
    w = pm_1.epoch_train(epoch=EPOCHS, learning_rate=LEARNING_RATE)
    pm1_details["testing_accuracy_avg"] += pm_1.max_accuracy["confusion_matrix"][0] / 10
    pm1_details["precision_avg"] += pm_1.max_accuracy["confusion_matrix"][1] / 10
    pm1_details["f1_avg"] += pm_1.max_accuracy["confusion_matrix"][2] / 10
    pm1_details["recall_avg"] += pm_1.max_accuracy["confusion_matrix"][3] / 10

    pm_2 = Perceptron(dataset=shuffled_dataset2, is_normalized=False)
    print("Executing model : pm_2")
    w = pm_2.epoch_train(epoch=EPOCHS, learning_rate=LEARNING_RATE)
    pm2_details["testing_accuracy_avg"] += pm_2.max_accuracy["confusion_matrix"][0] / 10
    pm2_details["precision_avg"] += pm_2.max_accuracy["confusion_matrix"][1] / 10
    pm2_details["f1_avg"] += pm_2.max_accuracy["confusion_matrix"][2] / 10
    pm2_details["recall_avg"] += pm_2.max_accuracy["confusion_matrix"][3] / 10

    pm_3 = Perceptron(dataset=dropped_dataset, is_normalized=True)
    print("Executing model : pm_3")
    w = pm_3.epoch_train(epoch=EPOCHS, learning_rate=LEARNING_RATE)
    pm3_details["testing_accuracy_avg"] += pm_3.max_accuracy["confusion_matrix"][0] / 10
    pm3_details["precision_avg"] += pm_3.max_accuracy["confusion_matrix"][1] / 10
    pm3_details["f1_avg"] += pm_3.max_accuracy["confusion_matrix"][2] / 10
    pm3_details["recall_avg"] += pm_3.max_accuracy["confusion_matrix"][3] / 10

    pm_4 = Perceptron(dataset=dataset_column_shuffled, is_normalized=False)
    print("Executing model : pm_4")
    w = pm_4.epoch_train(epoch=EPOCHS, learning_rate=LEARNING_RATE)
    pm4_details["testing_accuracy_avg"] += pm_4.max_accuracy["confusion_matrix"][0] / 10
    pm4_details["precision_avg"] += pm_4.max_accuracy["confusion_matrix"][1] / 10
    pm4_details["f1_avg"] += pm_4.max_accuracy["confusion_matrix"][2] / 10
    pm4_details["recall_avg"] += pm_4.max_accuracy["confusion_matrix"][3] / 10


In [4]:
print(f"{pm1_details=}")
print(f"{pm2_details=}")
print(f"{pm3_details=}")
print(f"{pm4_details=}")

pm1_details={'training_accuracy': 0, 'testing_accuracy_avg': 0.8225806451612904, 'precision_avg': 0.9435483870967742, 'f1_avg': 0.8764044943820226, 'recall_avg': 0.818181818181818}
pm2_details={'training_accuracy': 0, 'testing_accuracy_avg': 0.8763440860215054, 'precision_avg': 0.8759689922480619, 'f1_avg': 0.9076305220883532, 'recall_avg': 0.9416666666666664}
pm3_details={'training_accuracy': 0, 'testing_accuracy_avg': 0.9731182795698924, 'precision_avg': 0.9999999999999999, 'f1_avg': 0.9822064056939503, 'recall_avg': 0.9650349650349652}
pm4_details={'training_accuracy': 0, 'testing_accuracy_avg': 0.7978723404255318, 'precision_avg': 0.9421487603305787, 'f1_avg': 0.8571428571428573, 'recall_avg': 0.7862068965517243}


## FLDM

In [4]:
%%capture
fldm1_details = {
    "training_accuracy": 0,
    "accuracy_avg": 0,
    "precision_avg": 0,
    "f1_avg": 0,
    "recall_avg": 0
}
fldm1_normalized_details = {
    "training_accuracy": 0,
    "accuracy_avg": 0,
    "precision_avg": 0,
    "f1_avg": 0,
    "recall_avg": 0
}
fldm2_details = {
    "training_accuracy": 0,
    "accuracy_avg": 0,
    "precision_avg": 0,
    "f1_avg": 0,
    "recall_avg": 0
}
fldm2_normalized_details = {
    "training_accuracy": 0,
    "accuracy_avg": 0,
    "precision_avg": 0,
    "f1_avg": 0,
    "recall_avg": 0
}

for _ in range(10):
    # Read the csv file
    dataset = pd.read_csv('../dataset.csv')
    dataset = dataset.sample(frac=1)

    # Shuffling the dataset column wise
    dataset_column_shuffled = dataset.sample(frac=1, axis=1)
    # Convert cancer type into a new column
    dataset_column_shuffled["cancer_type"] = pd.factorize(
        dataset_column_shuffled["diagnosis"])[0]
    # Malignant is 0 and Benign is 1
    # Remove ID and diagnosis from the dataset
    dataset_column_shuffled.drop(['id', 'diagnosis'], axis=1, inplace=True)
    
    # Drop NA rows because in first one we shouldn't use NA
    dropped_dataset_column_shuffled = dataset_column_shuffled.dropna()

    # Convert cancer type into a new column
    dataset["cancer_type"] = pd.factorize(dataset["diagnosis"])[0]
    # Malignant is 0 and Benign is 1
    # Remove ID and diagnosis from the dataset
    dataset.drop(['id', 'diagnosis'], axis=1, inplace=True)
    
    # Drop NA rows because in first one we shouldn't use NA
    dropped_dataset = dataset.dropna()

    # FLDM1
    fldm1 = FisherLDA(dataset=dropped_dataset)
    fldm1.train()
    fldm1.check_testing_accuracy()
    fldm1_details["training_accuracy"] += fldm1.check_training_accuracy() / 10
    fldm1_details["accuracy_avg"] += fldm1.show_confusion_matrix()[0] / 10
    fldm1_details["precision_avg"] += fldm1.show_confusion_matrix()[1] / 10
    fldm1_details["f1_avg"] += fldm1.show_confusion_matrix()[2] / 10
    fldm1_details["recall_avg"] += fldm1.show_confusion_matrix()[3] / 10

    # FLDM1 with Normalized Dataset
    fldm1_normalized = FisherLDA(dataset=dataset, is_feature_engineered=1)
    fldm1_normalized.train()
    fldm1_normalized.check_testing_accuracy()
    fldm1_normalized_details["training_accuracy"] += fldm1_normalized.check_training_accuracy() / 10
    fldm1_normalized_details["accuracy_avg"] += fldm1_normalized.show_confusion_matrix()[
        0] / 10
    fldm1_normalized_details["precision_avg"] += fldm1_normalized.show_confusion_matrix()[
        1] / 10
    fldm1_normalized_details["f1_avg"] += fldm1_normalized.show_confusion_matrix()[
        2] / 10
    fldm1_normalized_details["recall_avg"] += fldm1_normalized.show_confusion_matrix()[
        3] / 10

    # FLDM2
    fldm2 = FisherLDA(dataset=dropped_dataset_column_shuffled)
    fldm2.train()
    fldm2.check_testing_accuracy()
    fldm2_details["training_accuracy"] += fldm2.check_training_accuracy() / 10
    fldm2_details["accuracy_avg"] += fldm2.show_confusion_matrix()[0] / 10
    fldm2_details["precision_avg"] += fldm2.show_confusion_matrix()[1] / 10
    fldm2_details["f1_avg"] += fldm2.show_confusion_matrix()[2] / 10
    fldm2_details["recall_avg"] += fldm2.show_confusion_matrix()[3] / 10

    # FLDM2 with Normalized Dataset
    fldm2_normalized = FisherLDA(
        dataset=dataset_column_shuffled, is_feature_engineered=1)
    fldm2_normalized.train()
    fldm2_normalized.check_testing_accuracy()
    fldm2_normalized_details["training_accuracy"] += fldm2_normalized.check_training_accuracy() / 10
    fldm2_normalized_details["accuracy_avg"] += fldm2_normalized.show_confusion_matrix()[
        0] / 10
    fldm2_normalized_details["precision_avg"] += fldm2_normalized.show_confusion_matrix()[
        1] / 10
    fldm2_normalized_details["f1_avg"] += fldm2_normalized.show_confusion_matrix()[
        2] / 10
    fldm2_normalized_details["recall_avg"] += fldm2_normalized.show_confusion_matrix()[
        3] / 10

In [5]:
print(f"{fldm1_details=}")
print(f"{fldm1_normalized_details=}")
print(f"{fldm2_details=}")
print(f"{fldm2_normalized_details=}")

fldm1_details={'training_accuracy': 0.9777188328912467, 'accuracy_avg': 0.9596774193548389, 'precision_avg': 0.9746214371245424, 'f1_avg': 0.9492712616650933, 'recall_avg': 0.9270876800737039}
fldm1_normalized_details={'training_accuracy': 0.978215223097113, 'accuracy_avg': 0.9617021276595744, 'precision_avg': 0.9757386548050596, 'f1_avg': 0.9514392175639453, 'recall_avg': 0.9300511851106507}
fldm2_details={'training_accuracy': 0.9777188328912467, 'accuracy_avg': 0.9596774193548389, 'precision_avg': 0.9746214371245424, 'f1_avg': 0.9492712616650933, 'recall_avg': 0.9270876800737039}
fldm2_normalized_details={'training_accuracy': 0.978215223097113, 'accuracy_avg': 0.9617021276595744, 'precision_avg': 0.9757386548050596, 'f1_avg': 0.9514392175639453, 'recall_avg': 0.9300511851106507}


## Logistic Regression

### LR Without Normalization

In [5]:
%%capture
final_permutations = np.zeros((45, 5))
descent = ("Batch", "Mini-Batch", "Stochastic")
threshold = (0.5, 0.3, 0.4, 0.6, 0.7)
learning_rate = (0.01, 0.001, 0.0001)

for _ in range(10):
    dataset = pd.read_csv('../dataset.csv')
    dataset = dataset.sample(frac=1)

    # Convert cancer type into a new column
    dataset["cancer_type"] = pd.factorize(dataset["diagnosis"])[0]
    # Malignant is 0 and Benign is 1

    # Remove ID and diagnosis from the dataset
    dataset.drop(['id', 'diagnosis'], axis=1, inplace=True)

    # Drop NA rows because in first one we shouldn't use NA
    dropped_dataset = dataset.dropna()
    
    # Logistic Regression 1
    lr1 = LogReg(dataset=dropped_dataset)
    matrix_of_45x5 = lr1.run_all_permutations(descents = descent, thresholds = threshold, learning_rates = learning_rate, epochs = 50, showGraph=False)
    final_permutations += matrix_of_45x5 / 10

In [6]:
# Order: Training Accuracy, Accuracy, Precision, recall, f1
print(final_permutations)

import pandas as pd

result = []

descent = ("Batch", "Mini-Batch", "Stochastic")
threshold = (0.5, 0.3, 0.4, 0.6, 0.7)
learning_rate = (0.01, 0.001, 0.0001)
i = 0
for d in descent:
            for lr in learning_rate:
                for t in threshold: 
                    g = [d, lr, t]
                    for m in final_permutations[i]:
                        g.append(m)
                    result.append(g)
                    i += 1
df = pd.DataFrame(result,
               columns =['Batch', 'Learning Rate', 'Threshold', 'Training Accuracy', 'Accuracy', 'Precision', 'F1', 'Recall'])
df.to_csv("../Result/log_reg_result.csv")

[[0.54376658 0.54462366        nan        nan 0.53164326]
 [0.54880637 0.54677419 0.74254332 0.44122164 0.5678271 ]
 [0.80981432 0.79623656 0.82458753 0.77540712 0.80186759]
 [0.88567639 0.87741935 0.85509975 0.87015714 0.89391496]
 [0.87665782 0.87096774 0.85224137 0.86313099 0.89063055]
 [0.89575597 0.89139785 0.8721688  0.88200273 0.89315608]
 [0.89549072 0.89139785 0.87229142 0.88217296 0.89349931]
 [0.89787798 0.89139785 0.87229142 0.88217296 0.89349931]
 [0.89734748 0.89193548 0.87244919 0.88285543 0.89478136]
 [0.89734748 0.89193548 0.87334931 0.88273197 0.89349931]
 [0.89655172 0.89193548 0.87334931 0.88273197 0.89349931]
 [0.89628647 0.89193548 0.87334931 0.88273197 0.89349931]
 [0.89602122 0.89193548 0.87334931 0.88273197 0.89349931]
 [0.89681698 0.89193548 0.87334931 0.88273197 0.89349931]
 [0.89681698 0.89193548 0.87334931 0.88273197 0.89349931]
 [0.53183024 0.54677419        nan        nan 0.58256769]
 [0.59363395 0.58548387        nan        nan 0.49105971]
 [0.75862069 0

### LR With Normalization

In [2]:
%%capture
final_permutations_normalised = np.zeros((45, 5))
descent = ("Batch", "Mini-Batch", "Stochastic")
threshold = (0.5, 0.3, 0.4, 0.6, 0.7)
learning_rate = (0.01, 0.001, 0.0001)

for _ in range(10):
    dataset = pd.read_csv('../dataset.csv')
    dataset = dataset.sample(frac=1)

    # Convert cancer type into a new column
    dataset["cancer_type"] = pd.factorize(dataset["diagnosis"])[0]
    # Malignant is 0 and Benign is 1

    # Remove ID and diagnosis from the dataset
    dataset.drop(['id', 'diagnosis'], axis=1, inplace=True)

    # Drop NA rows because in first one we shouldn't use NA
    dropped_dataset = dataset.dropna()

    # Logistic Regression 1
    lr2 = LogReg(dataset=dataset, is_feature_engineered=1)
    matrix_of_45x5_normalised = lr2.run_all_permutations(
        descents=descent, thresholds=threshold, learning_rates=learning_rate, epochs=50, showGraph=False)
    final_permutations_normalised += matrix_of_45x5_normalised / 10


In [3]:
print(final_permutations_normalised)

import pandas as pd

result = []

descent = ("Batch", "Mini-Batch", "Stochastic")
threshold = (0.5, 0.3, 0.4, 0.6, 0.7)
learning_rate = (0.01, 0.001, 0.0001)
i = 0
for d in descent:
            for lr in learning_rate:
                for t in threshold: 
                    g = [d, lr, t]
                    for m in final_permutations_normalised[i]:
                        g.append(m)
                    result.append(g)
                    i += 1
df = pd.DataFrame(result,
               columns =['Batch', 'Learning Rate', 'Threshold', 'Training Accuracy', 'Accuracy', 'Precision', 'F1', 'Recall'])
df.to_csv("../Result/log_reg_norm_result.csv")

[[0.98608924 0.97659574 0.97784676 0.97545594 0.97330866]
 [0.98372703 0.97446809 0.963021   0.97255979 0.98243733]
 [0.98792651 0.97712766 0.97147909 0.97482025 0.97858269]
 [0.98661417 0.97287234 0.98552443 0.97047715 0.95655056]
 [0.98372703 0.96914894 0.98671509 0.96571317 0.94613126]
 [0.98897638 0.975      0.97593613 0.97142012 0.96744813]
 [0.98582677 0.97234043 0.9576864  0.97017843 0.98338917]
 [0.98871391 0.97393617 0.96667854 0.9716211  0.97695023]
 [0.98661417 0.9712766  0.98207414 0.96880882 0.95650744]
 [0.9839895  0.96968085 0.98674533 0.96659552 0.94774417]
 [0.98950131 0.97393617 0.97435362 0.9702613  0.96657857]
 [0.9855643  0.97287234 0.95929842 0.97096479 0.98338917]
 [0.98871391 0.97287234 0.96584144 0.970433   0.97543085]
 [0.98661417 0.97074468 0.98040747 0.96807141 0.95650744]
 [0.9839895  0.96968085 0.98674533 0.96659552 0.94774417]
 [0.98713911 0.97659574 0.97710971 0.97542836 0.97404544]
 [0.98372703 0.97606383 0.96292711 0.97447144 0.98649461]
 [0.98713911 0